task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='list'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views


urlpatterns = [
    path('', views.index, name='index'),
    path('test_rollbar/', views.test_rollbar, name='test_rollbar'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext as _


class Label(models.Model):
    name = models.CharField(
        max_length=200, unique=True, verbose_name=_('Name'))

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models
from django.utils.translation import gettext as _


class Status(models.Model):
    name = models.CharField(
        max_length=200, unique=True, verbose_name=_('Name'))

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model
from task_manager.statuses.models import Status
from task_manager.labels.models import Label
from django.utils.translation import gettext as _


class Task(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name=_('Name'))
    description = models.TextField(verbose_name=_('Description'))
    created_at = models.DateTimeField(auto_now_add=True)

    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        related_name='status',
        verbose_name=_('Status'))

    author = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='author')
    executor = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name='executor',
        verbose_name=_('Assignee'))

    labels = models.ManyToManyField(
        Label,
        related_name='labels',
        verbose_name=_('Labels'),
        blank=True)

    def __str__(self):
        return self.name

task_manager/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.get_full_name()

task_manager/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


# class UserstrationForm(UserChangeForm):
#     class Meta:
#         model = get_user_model()
#         fields = [
#             'first_name',
#             'last_name',
#             'username',
#             'password1',
#             'password2'
# ]

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2'
        ]

task_manager/labels/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin
from task_manager.labels.models import Label
from task_manager.mixins import AuthRequireMixin
from django.contrib import messages
from django.shortcuts import redirect


class LabelListView(AuthRequireMixin, ListView):
    model = Label
    template_name = 'labels/list.html'


class LabelCreateView(SuccessMessageMixin, AuthRequireMixin, CreateView):
    model = Label
    template_name = 'labels/create.html'
    success_url = '/labels/'
    fields = ('name',)
    success_message = _('Label created successfully')


class LabelUpdateView(SuccessMessageMixin, AuthRequireMixin, UpdateView):
    model = Label
    template_name = 'labels/update.html'
    success_url = '/labels/'
    fields = ('name',)
    success_message = _('Label updated successfully')


class LabelDeleteView(SuccessMessageMixin, AuthRequireMixin, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = '/labels/'
    success_message = _('Label deleted successfully')

    def post(self, request, *args, **kwargs):
        if self.get_object().labels.exists():
            messages.error(self.request, _('You cannot delete label with tasks'))
            return redirect(self.success_url)

        return super().post(request, *args, **kwargs)

task_manager/statuses/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect

from task_manager.statuses.models import Status
from task_manager.mixins import AuthRequireMixin


class StatusListView(AuthRequireMixin, ListView):
    model = Status
    template_name = 'statuses/list.html'


class StatusCreateView(SuccessMessageMixin, AuthRequireMixin, CreateView):
    model = Status
    template_name = 'statuses/create.html'
    success_url = '/statuses/'
    fields = ('name',)
    success_message = _('Status created successfully')


class StatusUpdateView(SuccessMessageMixin, AuthRequireMixin, UpdateView):
    model = Status
    template_name = 'statuses/update.html'
    success_url = '/statuses/'
    fields = ('name',)
    success_message = _('Status updated successfully')


class StatusDeleteView(SuccessMessageMixin, AuthRequireMixin, DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_url = '/statuses/'
    success_message = _('Status deleted successfully')

    def post(self, request, *args, **kwargs):
        if self.get_object().status.exists():
            messages.error(self.request, _('You cannot delete status with tasks'))
            return redirect(self.success_url)

        return super().post(request, *args, **kwargs)

task_manager/tasks/views.py
import django.forms
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from task_manager.tasks.models import Task
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django_filters.views import FilterView
from django_filters import FilterSet
from django_filters.filters import BooleanFilter, ModelChoiceFilter
from task_manager.labels.models import Label
from task_manager.mixins import AuthRequireMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from django.shortcuts import redirect


class TaskAuthorTestMixin(UserPassesTestMixin):
    def test_func(self):
        if self.request.user != self.get_object().author:
            self.raise_exception = False
            self.permission_denied_message = \
                ('You cannot delete non-your task!')

            return False
        else:
            return True

    def handle_no_permission(self):
        messages.error(self.request, self.get_permission_denied_message())
        return redirect(reverse_lazy('tasks:list'))


class TaskFilter(FilterSet):
    self_tasks = BooleanFilter(
        widget=django.forms.CheckboxInput,
        field_name='author',
        method='filter_self_tasks',
        label=_('Only their own tasks'),
    )

    label = ModelChoiceFilter(
        queryset=Label.objects.all(),
        field_name='labels',
        label=_('Label'),
    )

    def filter_self_tasks(self, queryset, name, value):
        if value:
            return queryset.filter(author=self.request.user)
        return queryset

    class Meta:
        model = Task
        fields = ['status', 'executor', 'label', 'self_tasks']


class TaskListView(AuthRequireMixin, FilterView):
    model = Task
    template_name = 'tasks/list.html'
    filterset_class = TaskFilter


class TaskCreateView(AuthRequireMixin, SuccessMessageMixin, CreateView):
    model = Task
    template_name = 'tasks/create.html'
    success_url = '/tasks/'
    fields = ('name', 'description', 'status', 'executor', 'labels')
    success_message = _('Task created successfully')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskDetailsView(AuthRequireMixin, DetailView):
    model = Task
    template_name = 'tasks/details.html'


class TaskUpdateView(AuthRequireMixin, SuccessMessageMixin, UpdateView):
    model = Task
    template_name = 'tasks/update.html'
    success_url = '/tasks/'
    fields = ('name', 'description', 'status', 'executor', 'labels')
    success_message = _('Task updated successfully')


class TaskDeleteView(AuthRequireMixin, SuccessMessageMixin, TaskAuthorTestMixin, DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = '/tasks/'
    success_message = _('Task deleted successfully')

task_manager/users/views.py
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.views.generic import \
    ListView, CreateView, DeleteView, UpdateView
from task_manager.users.forms import UserRegistrationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext as _
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from django.shortcuts import redirect


class SelfUserTestMixin(UserPassesTestMixin):
    def test_func(self):
        if self.request.user != self.get_object():
            self.raise_exception = False
            self.permission_denied_message = \
                ('You cannot change not yourself! Please sign in.')

            return False
        else:
            return True

    def handle_no_permission(self):
        messages.error(self.request, self.get_permission_denied_message())
        return redirect(reverse_lazy('users:list'))


class UserListView(ListView):
    model = get_user_model()
    template_name = 'users/list.html'


class UserCreateView(SuccessMessageMixin, CreateView):
    model = get_user_model()
    template_name = 'users/create.html'
    form_class = UserRegistrationForm
    # fields = ('username', 'first_name', 'last_name', 'password1', 'password2')
    success_url = reverse_lazy('login')
    success_message = _('User registred successfully')


class UserUpdateView(SuccessMessageMixin, SelfUserTestMixin, UpdateView):
    model = get_user_model()
    template_name = 'users/update.html'
    form_class = UserRegistrationForm
    # fields = ('first_name', 'last_name', 'username', 'password')
    success_url = reverse_lazy('users:list')
    success_message = _('Пользователь успешно изменен')


class UserDeleteView(SuccessMessageMixin, SelfUserTestMixin, DeleteView):
    model = get_user_model()
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users:list')
    success_message = _('Пользователь успешно удален')

task_manager/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.contrib import messages


def index(request):
    return render(request, 'index.html')


def test_rollbar(request):
    a = None
    a.hello()
    return render(request, 'index.html')


class IndexView(TemplateView):
    template_name = 'index.html'


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'login.html'
    success_message = _('You are logged in.')


class UserLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, _('You are logged out.'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/tasks/create.html
{% extends "layout.html" %}

{% load django_bootstrap5 %}
{% load i18n %}
{% block title %}
    <h1 class="my-4">{% translate "Create task" %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="{% translate 'Create' %}">
    </form>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "common/delete.html" %}
{% load i18n %}

{% block title %}
{% translate "Delete task" %}
{% endblock %}

task_manager/templates/tasks/details.html
{% extends "layout.html" %}

{% load i18n %}
{% block title %}
<h1 class="my-4">{% translate "View task" %}</h1>
{% endblock %}

{% block content %}

<div class="card">
    <div class="card-header bg-secondary text-white">
        <h2>{{ object.name}}</h2>
    </div>
    <div class="card-body bg-light">
        <p>{{ object.description}}</p>
        <hr>
        <div class="container">
            <div class="row p-1">
                <div class="col">{% translate "Author" %}</div>
                <div class="col">{{ object.author }}</div>
            </div>
            <div class="row p-1">
                <div class="col">{% translate "Assignee" %}</div>
                <div class="col">{{ object.executor }}</div>
            </div>
            <div class="row p-1">
                <div class="col">{% translate "Status" %}</div>
                <div class="col">{{ object.status }}</div>
            </div>
            <div class="row p-1">
                <div class="col">{% translate "Created at" %}</div>
                <div class="col">{{ object.created_at }}</div>
            </div>
            <div class="row p-1">
                <div class="col">
                    <h6>{% translate "Labels" %}:</h6>
                    {% for label in object.labels.all %}
                    <span class="badge badge-secondary">{{ label.name }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="row p-1">
                <div class="col">
                    <a href="/tasks/{{ object.id }}/update/">{% translate "Update" %}</a>
                    <br>
                    <a href="/tasks/{{ object.id }}/delete/">{% translate "Delete" %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends "layout.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}{% translate "Tasks" %}{% endblock %}

{% block content %}

<a class="btn btn-primary mb-3" href="/tasks/create/">{% translate "Create task" %}</a>
<div class="card mb-3">
    <div class="card-body bg-light">
      <form class="form-inline center" method="get">
        {% bootstrap_form filter.form %}
          <input class="btn btn-primary" type="submit" value="{% translate 'Show' %}">
      </form>
    </div>
  </div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>{% translate "ID" %}</th>
            <th>{% translate "Name" %}</th>
            <th>{% translate "Status" %}</th>
            <th>{% translate "Author" %}</th>
            <th>{% translate "Executor" %}</th>
            <th>{% translate "Created at" %}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for task in task_list %}
        <tr>
            <td>{{ task.id }}</td>
            <td><a href="/tasks/{{ task.id }}">{{ task.name }}</a></td>
            <td>{{ task.status}}</td>
            <td>{{ task.author }}</td>
            <td>{{ task.executor }}</td>
            <td>{{ task.created_at }}</td>
            <td>
                <a href="/tasks/{{ task.id }}/update/">{% translate "Update" %}</a>
                <br>
                <a href="/tasks/{{ task.id }}/delete/">{% translate "Delete" %}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block title %}
<h1 class="my-4">{% translate "Update task" %}</h1>
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Update' %}">
</form>
{% endblock %}